(()=>{
const root=document.getElementById('gann');if(!root)return;
const style=document.createElement('style');style.textContent='.jd-row{cursor:pointer}.jd-row:hover{background:#f7f1fb}.jd-modal{position:fixed;inset:0;background:rgba(25,15,30,.55);display:grid;place-items:center;z-index:9999;padding:18px}.jd-card{background:#fff;border-radius:16px;padding:20px;width:min(620px,100%);max-height:90vh;overflow:auto}.jd-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.jd-field{background:#faf7f4;border:1px solid #eee7e2;border-radius:9px;padding:10px}.jd-field small{display:block;color:#766d79;text-transform:uppercase;font-weight:700}.jd-field b{display:block;margin-top:4px}.jd-card textarea{width:100%;min-height:100px;border:1px solid #e7dfda;border-radius:9px;padding:10px;margin-top:6px}@media(max-width:600px){.jd-grid{grid-template-columns:1fr}}';document.head.appendChild(style);
let trades=[];const tbody=document.getElementById('jrows');if(!tbody)return;
async function load(){const r=await fetch('/api/journal',{cache:'no-store'}),j=await r.json();if(r.ok)trades=j.trades||[]}
function open(t){const modal=document.createElement('div');modal.className='jd-modal';const fields=[['Date',t.trade_date],['Trade #',t.trade_no],['Side',t.side],['Entry time',t.entry_time],['Entry',t.entry],['Stop-loss',t.stop],['Target',t.target],['Exit time',t.exit_time],['Exit',t.exit],['Reason',t.reason],['Points',t.points],['Status',t.status]];modal.innerHTML=`<div class=jd-card><div class=lt><div><h2>Journal entry</h2><div class=ls>${t.trade_key||''}</div></div><button class=btn data-close>Close</button></div><div class=jd-grid style="margin-top:12px">${fields.map(x=>`<div class=jd-field><small>${x[0]}</small><b>${x[1]??'—'}</b></div>`).join('')}</div><label style="margin-top:14px">Diary notes</label><textarea>${t.notes||''}</textarea><div class=ac><button class="btn g" data-save>Save Notes</button><span class=st></span></div></div>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.querySelector('[data-save]').onclick=async()=>{const s=modal.querySelector('.st');s.textContent='Saving…';const r=await fetch(`/api/journal/${t.id}/notes`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes:modal.querySelector('textarea').value})}),j=await r.json();s.textContent=r.ok?'Saved.':(j.detail||'Save failed')};}
tbody.addEventListener('click',async e=>{const row=e.target.closest('tr');if(!row)return;await load();const rows=[...tbody.querySelectorAll('tr')],t=trades[rows.indexOf(row)];if(t)open(t)});
new MutationObserver(()=>[...tbody.querySelectorAll('tr')].forEach((r,i)=>{if(trades[i]||r.children.length>1){r.classList.add('jd-row');r.title='Click to open journal entry'}})).observe(tbody,{childList:true});
root.querySelector('[data-t="journal"]')?.addEventListener('click',load);load();
})();
