(()=>{const root=document.querySelector('#gann .L'),tabs=root?.querySelector('.tabs');if(!root||!tabs)return;
const button=document.createElement('button');button.dataset.t='options';button.textContent='Weekly Options';tabs.appendChild(button);
const pane=document.createElement('div');pane.id='p-options';pane.className='pane';pane.innerHTML=`
<div class="c def"><div class=lt><div><h2>Weekly Options Probability Backtest</h2><div class=ls>Runs both delta pairs against the exact same unchanged Same-Day 7,575.6 signal ledger.</div></div><span id=opDhanBadge class=badge><i></i><span>Checking option data</span></span></div>
<div class=chips><span class=chip>Test A: sell 0.80Δ + buy 0.40Δ</span><span class=chip>Test B: sell 0.50Δ + buy 0.20Δ</span><span class=chip>Nearest weekly expiry</span><span class=chip>Fixed quantity 1,300</span><span class=chip>Exit with underlying trade</span></div></div>
<div class="gr g2"><div class=c><h2>1 · Secure Dhan data setup</h2><div class=note>Zerodha remains the source for the locked underlying signals. Dhan is used only because its official API supplies five years of expired weekly option candles. Generate a 24-hour Access Token in Dhan Web → My Profile → Access DhanHQ APIs.</div><div class="gr g2" style="margin-top:12px"><div><label>Dhan Client ID</label><input id=opClient autocomplete=off></div><div><label>24-hour Access Token</label><input id=opToken type=password autocomplete=off></div></div><div class=ac><button id=opSave class="btn g">Save Dhan Connection</button><span id=opSetupStatus class=st></span></div></div>
<div class=c><h2>2 · Fixed strategy mapping</h2><div class=note><b>SHORT signal:</b> bear Call spread. <b>LONG signal:</b> bull Put spread.<br>Each signal is priced twice: sold/bought deltas <b>0.80/0.40</b> and <b>0.50/0.20</b>. Both legs enter and exit on the underlying timestamps.</div></div></div>
<div class=c><h2>3 · Run both linked options tests</h2><div class="gr g3"><div><label>From</label><input id=opFrom type=date value="2025-09-05"></div><div><label>To</label><input id=opTo type=date value="2026-09-15"></div><div><label>Quantity (units)</label><input id=opQty type=number value=1300></div></div><div class=ac><button id=opRun class="btn p">Run Both Delta Tests</button><span id=opStatus class=st>Connect the authorised option-price source, then run.</span></div><div class=prog style="margin-top:12px"><i id=opBar></i></div></div>
<div id=opResults class=hide><div class=c><h2>Delta-pair comparison</h2><div class=tw><table><thead><tr><th>Pair</th><th>Trades</th><th>Total ₹ P/L</th><th>Win rate</th><th>Profit factor</th><th>Max DD ₹</th><th>Missing</th></tr></thead><tbody id=opCompare></tbody></table></div></div><div class=c style="margin-top:13px"><h2>Trade-by-trade option ledger</h2><div class=tw><table><thead><tr><th>Pair</th><th>Date</th><th>#</th><th>Signal</th><th>Spread</th><th>Short strike</th><th>Short Δ</th><th>Short in/out</th><th>Hedge strike</th><th>Hedge Δ</th><th>Hedge in/out</th><th>Credit</th><th>Spread pts</th><th>Qty</th><th>₹ P/L</th><th>Status</th></tr></thead><tbody id=opRows></tbody></table></div></div></div>`;
root.appendChild(pane);const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0}),num=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
function activate(){root.querySelectorAll('[data-t]').forEach(x=>x.classList.toggle('on',x===button));root.querySelectorAll('.pane').forEach(x=>x.classList.toggle('on',x===pane));status()}
button.onclick=activate;
async function api(url,opt){const r=await fetch(url,opt),t=await r.text();let j;try{j=JSON.parse(t)}catch{throw Error(t||`HTTP ${r.status}`)}if(!r.ok)throw Error(j.detail||t);return j}
async function status(){try{const j=await api('/api/dhan/status');$('opDhanBadge').classList.toggle('good',j.configured);$('opDhanBadge').querySelector('span').textContent=j.configured?'Dhan configured':'Dhan setup required';if(j.client_id)$('opClient').value=j.client_id}catch(e){$('opSetupStatus').textContent=e.message}}
$('opSave').onclick=async()=>{const client_id=$('opClient').value.trim(),access_token=$('opToken').value.trim();if(!client_id||!access_token)return $('opSetupStatus').textContent='Enter Client ID and Access Token.';try{await api('/api/dhan/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id,access_token})});$('opToken').value='';$('opSetupStatus').textContent='Saved securely. Token is valid for 24 hours.';status()}catch(e){$('opSetupStatus').textContent='Error: '+e.message}};
function render(j){$('opResults').classList.remove('hide');$('opCompare').innerHTML=(j.comparisons||[]).map(s=>`<tr><td><b>${s.pair}</b></td><td>${s.trades||0}</td><td class="${s.total_pnl>=0?'pos':'neg'}">${money(s.total_pnl)}</td><td>${num(s.win_rate,1)}%</td><td>${num(s.profit_factor,2)}</td><td>${money(s.max_drawdown)}</td><td>${s.missing||0}</td></tr>`).join('');$('opRows').innerHTML=(j.trades||[]).map(x=>x.option_status==='OK'?`<tr><td><b>${x.pair}</b></td><td>${x.date}</td><td>${x.trade_no}</td><td>${x.underlying_side}</td><td>${x.option_type==='CALL'?'Bear Call':'Bull Put'}</td><td>${x.short_strike}</td><td>${num(x.short_delta,3)}</td><td>${num(x.short_entry)}/${num(x.short_exit)}</td><td>${x.hedge_strike}</td><td>${num(x.hedge_delta,3)}</td><td>${num(x.hedge_entry)}/${num(x.hedge_exit)}</td><td>${num(x.entry_credit)}</td><td class="${x.spread_points>=0?'pos':'neg'}">${num(x.spread_points)}</td><td>${x.quantity}</td><td class="${x.pnl>=0?'pos':'neg'}">${money(x.pnl)}</td><td>OK</td></tr>`:`<tr><td><b>${x.pair}</b></td><td>${x.date}</td><td>${x.trade_no}</td><td>${x.side||''}</td><td colspan=11></td><td class=neg>${x.option_status}</td></tr>`).join('')}
$('opRun').onclick=async()=>{const body={from_date:$('opFrom').value,to_date:$('opTo').value,quantity:+$('opQty').value};$('opRun').disabled=true;$('opStatus').textContent='Starting both linked delta-pair tests…';try{const j=await api('/api/options/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const timer=setInterval(async()=>{try{const x=await api('/api/options/backtest/'+j.id),p=x.total?Math.round((x.done||0)*100/x.total):0;$('opBar').style.width=p+'%';$('opStatus').textContent=x.message||x.stage;if(x.status==='complete'){clearInterval(timer);$('opRun').disabled=false;render(x);$('opStatus').textContent='Completed both delta-pair tests'}else if(x.status==='error'){clearInterval(timer);$('opRun').disabled=false;$('opStatus').textContent='Error: '+x.error}}catch(e){clearInterval(timer);$('opRun').disabled=false;$('opStatus').textContent='Error: '+e.message}},2500)}catch(e){$('opRun').disabled=false;$('opStatus').textContent='Error: '+e.message}};status()})();
