(()=>{const root=document.querySelector('#gann .L'),tabs=root?.querySelector('.tabs');if(!root||!tabs)return;
const button=document.createElement('button');button.dataset.t='options';button.textContent='Weekly Options';tabs.appendChild(button);
const pane=document.createElement('div');pane.id='p-options';pane.className='pane';pane.innerHTML=`
<div class="c def"><div class=lt><div><h2>Weekly Options Probability Backtest</h2><div class=ls>Uses the unchanged Same-Day 7,575.6 trades as signals and real Dhan expired weekly NIFTY option premiums.</div></div><span id=opDhanBadge class=badge><i></i><span>Checking Dhan</span></span></div>
<div class=chips><span class=chip>SHORT → sell 0.50Δ Call + buy 0.20Δ Call</span><span class=chip>LONG → sell 0.50Δ Put + buy 0.20Δ Put</span><span class=chip>Nearest weekly expiry</span><span class=chip>Fixed quantity 1,300</span><span class=chip>Exit with underlying trade</span></div></div>
<div class="gr g2"><div class=c><h2>1 · Secure Dhan data setup</h2><div class=note>Zerodha remains the source for the locked underlying signals. Dhan is used only because its official API supplies five years of expired weekly option candles. Generate a 24-hour Access Token in Dhan Web → My Profile → Access DhanHQ APIs.</div><div class="gr g2" style="margin-top:12px"><div><label>Dhan Client ID</label><input id=opClient autocomplete=off></div><div><label>24-hour Access Token</label><input id=opToken type=password autocomplete=off></div></div><div class=ac><button id=opSave class="btn g">Save Dhan Connection</button><span id=opSetupStatus class=st></span></div></div>
<div class=c><h2>2 · Fixed strategy mapping</h2><div class=note><b>Falling-market / SHORT signal:</b> bear call spread — sell closest 0.50Δ Call and buy closest 0.20Δ Call.<br><b>Rising-market / LONG signal:</b> bull put spread — sell closest 0.50Δ Put and buy closest 0.20Δ Put.<br>Both legs enter and exit on the underlying trade timestamps. No estimated premiums are used.</div></div></div>
<div class=c><h2>3 · Run linked options backtest</h2><div class="gr g5"><div><label>From</label><input id=opFrom type=date value="2025-09-05"></div><div><label>To</label><input id=opTo type=date value="2026-09-15"></div><div><label>Quantity (units)</label><input id=opQty type=number value=1300></div><div><label>Sell delta</label><input id=opSellDelta type=number step=.01 value=.50></div><div><label>Hedge delta</label><input id=opHedgeDelta type=number step=.01 value=.20></div></div><div class=ac><button id=opRun class="btn p">Run Weekly Options Backtest</button><span id=opStatus class=st>Connect Zerodha and Dhan, then run.</span></div><div class=prog style="margin-top:12px"><i id=opBar></i></div></div>
<div id=opResults class=hide><div class=K><div class=k><span>Option trades</span><b id=opTrades>0</b></div><div class=k><span>Total ₹ P/L</span><b id=opPnl>0</b></div><div class=k><span>Win rate</span><b id=opWin>0</b></div><div class=k><span>Profit factor</span><b id=opPf>0</b></div><div class=k><span>Max drawdown ₹</span><b id=opDd>0</b></div><div class=k><span>Missing data</span><b id=opMissing>0</b></div></div><div class=c style="margin-top:13px"><h2>Trade-by-trade option ledger</h2><div class=tw><table><thead><tr><th>Date</th><th>#</th><th>Signal</th><th>Spread</th><th>Short strike</th><th>Short Δ</th><th>Short in/out</th><th>Hedge strike</th><th>Hedge Δ</th><th>Hedge in/out</th><th>Credit</th><th>Spread pts</th><th>Qty</th><th>₹ P/L</th><th>Status</th></tr></thead><tbody id=opRows></tbody></table></div></div></div>`;
root.appendChild(pane);const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0}),num=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
function activate(){root.querySelectorAll('[data-t]').forEach(x=>x.classList.toggle('on',x===button));root.querySelectorAll('.pane').forEach(x=>x.classList.toggle('on',x===pane));status()}
button.onclick=activate;
async function api(url,opt){const r=await fetch(url,opt),t=await r.text();let j;try{j=JSON.parse(t)}catch{throw Error(t||`HTTP ${r.status}`)}if(!r.ok)throw Error(j.detail||t);return j}
async function status(){try{const j=await api('/api/dhan/status');$('opDhanBadge').classList.toggle('good',j.configured);$('opDhanBadge').querySelector('span').textContent=j.configured?'Dhan configured':'Dhan setup required';if(j.client_id)$('opClient').value=j.client_id}catch(e){$('opSetupStatus').textContent=e.message}}
$('opSave').onclick=async()=>{const client_id=$('opClient').value.trim(),access_token=$('opToken').value.trim();if(!client_id||!access_token)return $('opSetupStatus').textContent='Enter Client ID and Access Token.';try{await api('/api/dhan/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id,access_token})});$('opToken').value='';$('opSetupStatus').textContent='Saved securely. Token is valid for 24 hours.';status()}catch(e){$('opSetupStatus').textContent='Error: '+e.message}};
function render(j){const s=j.summary||{};$('opResults').classList.remove('hide');$('opTrades').textContent=s.trades||0;$('opPnl').textContent=money(s.total_pnl);$('opPnl').className=Number(s.total_pnl)>=0?'pos':'neg';$('opWin').textContent=num(s.win_rate,1)+'%';$('opPf').textContent=num(s.profit_factor,2);$('opDd').textContent=money(s.max_drawdown);$('opMissing').textContent=s.missing||0;$('opRows').innerHTML=(j.trades||[]).map(x=>x.option_status==='OK'?`<tr><td>${x.date}</td><td>${x.trade_no}</td><td>${x.underlying_side}</td><td>${x.option_type==='CALL'?'Bear Call':'Bull Put'}</td><td>${x.short_strike}</td><td>${num(x.short_delta,3)}</td><td>${num(x.short_entry)}/${num(x.short_exit)}</td><td>${x.hedge_strike}</td><td>${num(x.hedge_delta,3)}</td><td>${num(x.hedge_entry)}/${num(x.hedge_exit)}</td><td>${num(x.entry_credit)}</td><td class="${x.spread_points>=0?'pos':'neg'}">${num(x.spread_points)}</td><td>${x.quantity}</td><td class="${x.pnl>=0?'pos':'neg'}">${money(x.pnl)}</td><td>OK</td></tr>`:`<tr><td>${x.date}</td><td>${x.trade_no}</td><td>${x.side||''}</td><td colspan=11></td><td class=neg>${x.option_status}</td></tr>`).join('')}
$('opRun').onclick=async()=>{const body={from_date:$('opFrom').value,to_date:$('opTo').value,quantity:+$('opQty').value,short_delta:+$('opSellDelta').value,hedge_delta:+$('opHedgeDelta').value};$('opRun').disabled=true;$('opStatus').textContent='Starting linked spot + weekly options backtest…';try{const j=await api('/api/options/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const timer=setInterval(async()=>{try{const x=await api('/api/options/backtest/'+j.id),p=x.total?Math.round((x.done||0)*100/x.total):0;$('opBar').style.width=p+'%';$('opStatus').textContent=x.message||x.stage;if(x.status==='complete'){clearInterval(timer);$('opRun').disabled=false;render(x);$('opStatus').textContent=`Completed · ${x.summary.trades} priced trades · ${money(x.summary.total_pnl)}`}else if(x.status==='error'){clearInterval(timer);$('opRun').disabled=false;$('opStatus').textContent='Error: '+x.error}}catch(e){clearInterval(timer);$('opRun').disabled=false;$('opStatus').textContent='Error: '+e.message}},2500)}catch(e){$('opRun').disabled=false;$('opStatus').textContent='Error: '+e.message}};status()})();
