(()=>{const $=id=>document.getElementById(id);if(!$('dflt')||!$('sym'))return;
const PROD={sym:'NIFTY 50',fr:'2025-09-05',to:'2026-09-15',ti:'5',ci:'1',wma:'.382',gs:'.125',ts:'both',em:'trigger',dir:'both',sb:'stop_first',tm:'points',tv:'100',sm:'gann',sv:'0',re:'false',mx:'1',st:'09:15',et:'15:30',cost:'0',slip:'0'};
const CLOSE={...PROD,em:'close',sb:'exclude'};const REENTRY={...PROD,re:'true',mx:''};
const card=$('dflt').closest('.c'),head=card?.querySelector('h2'),sub=card?.querySelector('.ls'),chips=card?.querySelector('.chips'),wrap=$('dflt').parentElement;
if(head)head.textContent='Strategy Presets';if(sub)sub.textContent='Original production setup is protected. Later close-confirmation and re-entry versions stay separate.';$('dflt').textContent='Original Production 7750';
const cb=document.createElement('button');cb.id='closePreset';cb.className='btn';cb.textContent='Later · 1-Min Close';wrap?.appendChild(cb);const rb=document.createElement('button');rb.id='reentryPreset';rb.className='btn';rb.textContent='Re-entry Version';wrap?.appendChild(rb);const ab=document.createElement('button');ab.id='audit7750';ab.className='btn g';ab.textContent='Audit Original 7750';wrap?.appendChild(ab);
const note=document.createElement('div');note.id='presetNote';note.className='note';note.style.marginTop='10px';card?.appendChild(note);const audit=document.createElement('div');audit.id='auditBox';audit.className='note';audit.style.marginTop='10px';audit.style.display='none';card?.appendChild(audit);
function ensureTrigger(){const e=$('em');if(e&&!Array.from(e.options).some(o=>o.value==='trigger')){const o=document.createElement('option');o.value='trigger';o.textContent='Immediate Gann trigger';e.insertBefore(o,e.firstChild)}}ensureTrigger();
function clearOld(){const res=$('res');if(res)res.classList.add('hide');['net','ntr','win','pf','dd','avg','kt','ksl','kl','ksh','best','worst'].forEach(id=>{const e=$(id);if(e)e.textContent='—'});const e=$('eq');if(e)e.innerHTML='';const m=$('months');if(m)m.innerHTML='';const t=$('trades');if(t)t.innerHTML='';}
function set(p,name){Object.entries(p).forEach(([k,v])=>{const e=$(k);if(e)e.value=v});$('dflt').classList.toggle('v',name==='Original Production 7750');cb.classList.toggle('v',name==='Later · 1-Min Close');rb.classList.toggle('v',name==='Re-entry Version');clearOld();audit.style.display='none';
if(name==='Original Production 7750'){note.innerHTML='<b>Original Production 7750</b> · source screenshot: 05 Sep 2025 → 15 Sep 2026. First Support/Resistance touch becomes Square-of-9 input. First Gann Buy/Sell trigger creates the only trade. Entry = exact Gann trigger. Stop = opposite Gann level. Target = 100 points. Benchmark: 236 trades · 133 wins / 103 losses · 56.4% win · +7,750.3 points · 104 targets · 95 stop exits · 110 long / 126 short · 116 support-first / 120 resistance-first.';chips.innerHTML='<span class=chip>05 Sep 2025 → 15 Sep 2026</span><span class=chip>WMA .382</span><span class=chip>5m first touch</span><span class=chip>Exact Gann trigger entry</span><span class=chip>100 pt target</span><span class=chip>Opposite Gann SL</span><span class=chip>ONE trade/day</span><span class=chip>No re-entry</span>'}
else if(name==='Later · 1-Min Close'){note.innerHTML='<b>Later · 1-Min Close</b> · waits for a 1-minute candle close beyond Buy Above / Sell Below and enters at that close.';chips.innerHTML='<span class=chip>WMA .382</span><span class=chip>5m first touch</span><span class=chip>1m close</span><span class=chip>100 pt target</span><span class=chip>ONE trade/day</span>'}
else{note.innerHTML='<b>Re-entry Version</b> · exact Gann trigger entry with multiple same-day re-entries after exits.';chips.innerHTML='<span class=chip>WMA .382</span><span class=chip>5m first touch</span><span class=chip>Exact Gann trigger</span><span class=chip>100 pt target</span><span class=chip>Unlimited re-entry</span>'}
const st=$('stat');if(st)st.textContent=name+' loaded. Old result cleared — click Run Backtest for a fresh result.';}
const baseBody=(sm,sb='stop_first')=>({symbol:'NIFTY 50',from_date:'2025-09-05',to_date:'2026-09-15',touch_interval:5,confirm_interval:1,wma_factor:.382,gann_step:.125,touch_side:'both',entry_mode:'trigger',direction:'both',same_bar_policy:sb,target_mode:'points',target_value:100,stop_mode:sm,stop_value:0,reentry:false,max_trades_per_day:1,start_time:'09:15',end_time:'15:30',cost_points:0,slippage_points:0});
async function call(body){const r=await fetch('/api/lab/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let j;try{j=JSON.parse(t)}catch{throw Error(t||'Invalid response')}if(!r.ok)throw Error(j.detail||t);return j}
ab.onclick=async()=>{audit.style.display='block';audit.innerHTML='<b>Recovery Audit running…</b> Same Zerodha data, exact original dates. Please wait.';ab.disabled=true;const vars=[['SL on price touch','gann','stop_first'],['SL on 1m close','gann_close_1m','stop_first'],['SL on 5m close','gann_close_5m','stop_first'],['SL active in entry minute','gann_touch_entrybar','stop_first'],['Touch SL · target first if same minute','gann','target_first']];try{const rows=[];for(const [name,sm,sb] of vars){const j=await call(baseBody(sm,sb)),s=j.summary;const score=Math.abs((s.trades||0)-236)*40+Math.abs((s.wins||0)-133)*20+Math.abs((s.targets||0)-104)*25+Math.abs((s.stops||0)-95)*25+Math.abs((s.long_trades||0)-110)*10+Math.abs((s.short_trades||0)-126)*10+Math.abs((s.support_first||0)-116)*8+Math.abs((s.resistance_first||0)-120)*8+Math.abs((s.total_points||0)-7750.3);rows.push({name,s,score})}rows.sort((a,b)=>a.score-b.score);audit.innerHTML='<b>Original benchmark:</b> 236 trades · 133 wins · 104 targets · 95 stops · +7,750.3 pts · Long 110 / Short 126 · Support 116 / Resistance 120<div style="overflow:auto;margin-top:10px"><table style="width:100%;font-size:11px"><thead><tr><th>Stop rule</th><th>Trades</th><th>Wins</th><th>Targets</th><th>Stops</th><th>Points</th><th>L/S</th><th>Sup/Res</th><th>Match gap</th></tr></thead><tbody>'+rows.map((x,i)=>`<tr style="${i===0?'font-weight:800;background:#eef9f4':''}"><td>${i===0?'★ ':''}${x.name}</td><td>${x.s.trades}</td><td>${x.s.wins}</td><td>${x.s.targets}</td><td>${x.s.stops}</td><td>${Number(x.s.total_points).toFixed(1)}</td><td>${x.s.long_trades||0}/${x.s.short_trades||0}</td><td>${x.s.support_first||0}/${x.s.resistance_first||0}</td><td>${Math.round(x.score)}</td></tr>`).join('')+'</tbody></table></div><div style="margin-top:8px">★ = closest structural match to the original screenshot; it is not hard-coded to win.</div>'}catch(e){audit.innerHTML='<b>Audit error:</b> '+e.message}finally{ab.disabled=false}};
$('dflt').onclick=()=>set(PROD,'Original Production 7750');cb.onclick=()=>set(CLOSE,'Later · 1-Min Close');rb.onclick=()=>set(REENTRY,'Re-entry Version');set(PROD,'Original Production 7750');})();