(()=>{const $=id=>document.getElementById(id);if(!$('dflt')||!$('sym'))return;
const PROD={sym:'NIFTY 50',fr:'2025-09-05',to:'2026-09-15',ti:'5',ci:'1',wma:'.382',gs:'.125',ts:'both',em:'trigger',dir:'both',sb:'stop_first',tm:'points',tv:'100',sm:'gann',sv:'0',re:'true',mx:'2',st:'09:15',et:'15:30',cost:'0',slip:'0'};
const CLOSE={...PROD,ts:'both',em:'close',sb:'exclude',re:'false',mx:'1'};
const REENTRY={...PROD,ts:'both',re:'true',mx:''};
const RECALC={...PROD,ts:'both_recalc',re:'true',mx:'2'};
const SAME_DAY={...PROD,ts:'both_recalc',re:'true',mx:'2'};
const card=$('dflt').closest('.c'),head=card?.querySelector('h2'),sub=card?.querySelector('.ls'),chips=card?.querySelector('.chips'),wrap=$('dflt').parentElement;
if(head)head.textContent='Same-Day WMA/Gann Research';
if(sub)sub.textContent='One editable window for Support + Resistance trades. Presets only fill fields — nothing is locked.';
$('dflt').textContent='7750 Reference Preset';
const sd=document.createElement('button');sd.id='sameDayBoth';sd.className='btn p';sd.textContent='Same-Day Both S/R';wrap?.prepend(sd);
const cb=document.createElement('button');cb.id='closePreset';cb.className='btn';cb.textContent='1-Min Close Variant';wrap?.appendChild(cb);
const rb=document.createElement('button');rb.id='reentryPreset';rb.className='btn';rb.textContent='Fresh-Cross Re-entry';wrap?.appendChild(rb);
const ob=document.createElement('button');ob.id='oppRecalcPreset';ob.className='btn';ob.textContent='Opposite WMA Recalc';wrap?.appendChild(ob);
const ab=document.createElement('button');ab.id='audit7750';ab.className='btn g';ab.textContent='Audit 7750 Reference';wrap?.appendChild(ab);
const note=document.createElement('div');note.id='presetNote';note.className='note';note.style.marginTop='10px';card?.appendChild(note);
const audit=document.createElement('div');audit.id='auditBox';audit.className='note';audit.style.marginTop='10px';audit.style.display='none';card?.appendChild(audit);
function ensureOptions(){const e=$('em');if(e&&!Array.from(e.options).some(o=>o.value==='trigger')){const o=document.createElement('option');o.value='trigger';o.textContent='Immediate Gann trigger';e.insertBefore(o,e.firstChild)}const t=$('ts');if(t&&!Array.from(t.options).some(o=>o.value==='both_recalc')){const o=document.createElement('option');o.value='both_recalc';o.textContent='Support + Resistance with opposite-level recalc';t.appendChild(o)}}ensureOptions();
function clearOld(){const res=$('res');if(res)res.classList.add('hide');['net','ntr','win','pf','dd','avg','kt','ksl','kl','ksh','best','worst'].forEach(id=>{const e=$(id);if(e)e.textContent='—'});const e=$('eq');if(e)e.innerHTML='';const m=$('months');if(m)m.innerHTML='';const t=$('trades');if(t)t.innerHTML='';}
function applyFields(p){Object.entries(p).forEach(([k,v])=>{const e=$(k);if(e)e.value=v})}
function clearMarks(){[$('dflt'),sd,cb,rb,ob].forEach(x=>x&&x.classList.remove('v'))}
function set(p,name){applyFields(p);clearMarks();if(name==='7750 Reference Preset')$('dflt').classList.add('v');if(name==='Same-Day Both S/R')sd.classList.add('v');if(name==='1-Min Close Variant')cb.classList.add('v');if(name==='Fresh-Cross Re-entry')rb.classList.add('v');if(name==='Opposite WMA Recalc')ob.classList.add('v');clearOld();audit.style.display='none';
if(name==='7750 Reference Preset'){note.innerHTML='<b>7750 Reference Preset</b> · a first 5-minute red body greater than 120 points blocks LONG; a green body greater than 120 blocks SHORT. The permitted opposite direction waits for its Gann level. A taken trade that hits Gann SL may reverse once immediately at that level. Audit 7750 now uses these same combined rules.';chips.innerHTML='<span class=chip>First 5m body filter</span><span class=chip>120 points</span><span class=chip>Opposite Gann entry</span><span class=chip>One SL reverse</span><span class=chip>100 pt target</span>'}
else if(name==='Same-Day Both S/R'){note.innerHTML='<b>Same-Day Both S/R</b> · one combined window and one ledger for the whole day. The first Support/Resistance touch can create trade #1. After it finishes, if the opposite WMA level is later reached, that level can create a fresh Gann grid and trade #2. All fields below remain editable.';chips.innerHTML='<span class=chip>Support + Resistance together</span><span class=chip>Same-day ledger</span><span class=chip>Opposite WMA recalc</span><span class=chip>Fresh-cross logic</span><span class=chip>Editable max trades</span><span class=chip>Nothing locked</span>'}
else if(name==='1-Min Close Variant'){note.innerHTML='<b>1-Min Close Variant</b> · waits for a 1-minute candle close beyond the Gann trigger. This is just a starting preset; change anything you want.';chips.innerHTML='<span class=chip>Fully editable</span><span class=chip>1m close</span><span class=chip>Support + Resistance selectable</span>'}
else if(name==='Fresh-Cross Re-entry'){note.innerHTML='<b>Fresh-Cross Re-entry</b> · re-entry requires price to re-arm across the trigger before another same-side trade. All parameters remain editable.';chips.innerHTML='<span class=chip>Fresh-cross re-entry</span><span class=chip>No duplicate same-level entries</span><span class=chip>Fully editable</span>'}
else{note.innerHTML='<b>Opposite WMA Recalc</b> · after the first WMA-based trade finishes, the opposite WMA level can become a new Square-of-9 reference. Support and Resistance trades appear in the same ledger. All controls remain editable.';chips.innerHTML='<span class=chip>Both S/R in one ledger</span><span class=chip>Opposite WMA = new Gann grid</span><span class=chip>Fully editable</span>'}
const st=$('stat');if(st)st.textContent=name+' loaded as a starting point. You can change any setting before Run Backtest.';}
const baseBody=()=>({symbol:'NIFTY 50',from_date:'2025-09-05',to_date:'2026-09-15',touch_interval:5,confirm_interval:1,wma_factor:.382,gann_step:.125,touch_side:'both',entry_mode:'trigger',direction:'both',same_bar_policy:'stop_first',target_mode:'points',target_value:100,stop_mode:'gann',stop_value:0,reentry:true,max_trades_per_day:2,start_time:'09:15',end_time:'15:30',cost_points:0,slippage_points:0});
async function call(body){const r=await fetch('/api/lab/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let j;try{j=JSON.parse(t)}catch{throw Error(t||'Invalid response')}if(!r.ok)throw Error(j.detail||t);return j}
ab.onclick=async()=>{audit.style.display='block';audit.innerHTML='<b>7750 audit running…</b> Includes the first 5-minute body filter and one Gann-SL opposite trade as core strategy conditions. Your visible form settings are not changed.';ab.disabled=true;try{const j=await call(baseBody()),s=j.summary;audit.innerHTML='<b>Audit 7750 — combined rules:</b> first 5m red body &gt;120 blocks LONG · green body &gt;120 blocks SHORT · one opposite trade after Gann SL<div style="overflow:auto;margin-top:10px"><table style="width:100%;font-size:11px"><thead><tr><th>Trades</th><th>Wins</th><th>Targets</th><th>Stops</th><th>Reverse</th><th>Points</th><th>L/S</th><th>Large red/green</th></tr></thead><tbody><tr style="font-weight:800;background:#eef9f4"><td>'+(s.trades||0)+'</td><td>'+(s.wins||0)+'</td><td>'+(s.targets||0)+'</td><td>'+(s.stops||0)+'</td><td>'+(s.reverse_trades||0)+'</td><td>'+Number(s.total_points||0).toFixed(1)+'</td><td>'+(s.long_trades||0)+'/'+(s.short_trades||0)+'</td><td>'+(s.large_red_first_candle||0)+'/'+(s.large_green_first_candle||0)+'</td></tr></tbody></table></div><div style="margin-top:8px">Audit finished. These conditions are now included in Audit 7750, not tested separately.</div>'}catch(e){audit.innerHTML='<b>Audit error:</b> '+e.message}finally{ab.disabled=false}};
$('dflt').onclick=()=>set(PROD,'7750 Reference Preset');sd.onclick=()=>set(SAME_DAY,'Same-Day Both S/R');cb.onclick=()=>set(CLOSE,'1-Min Close Variant');rb.onclick=()=>set(REENTRY,'Fresh-Cross Re-entry');ob.onclick=()=>set(RECALC,'Opposite WMA Recalc');set(SAME_DAY,'Same-Day Both S/R');})();
