(()=>{const $=id=>document.getElementById(id);if(!$('dflt')||!$('sym'))return;
const PROD={sym:'NIFTY 50',fr:'2025-09-05',to:'2026-09-15',ti:'5',ci:'1',wma:'.382',gs:'.125',ts:'both',em:'trigger',dir:'both',sb:'stop_first',tm:'points',tv:'100',sm:'gann',sv:'0',re:'false',mx:'1',st:'09:15',et:'15:30',cost:'0',slip:'0'};
const CLOSE={...PROD,em:'close',sb:'exclude'};
const REENTRY={...PROD,re:'true',mx:''};
const card=$('dflt').closest('.c'),head=card?.querySelector('h2'),sub=card?.querySelector('.ls'),chips=card?.querySelector('.chips'),wrap=$('dflt').parentElement;
if(head)head.textContent='Strategy Presets';if(sub)sub.textContent='Original production setup is protected. Later close-confirmation and re-entry versions stay separate.';
$('dflt').textContent='Original Production 7750';
const cb=document.createElement('button');cb.id='closePreset';cb.className='btn';cb.textContent='Later · 1-Min Close';wrap?.appendChild(cb);
const rb=document.createElement('button');rb.id='reentryPreset';rb.className='btn';rb.textContent='Re-entry Version';wrap?.appendChild(rb);
const note=document.createElement('div');note.id='presetNote';note.className='note';note.style.marginTop='10px';card?.appendChild(note);
function ensureTrigger(){const e=$('em');if(e&&!Array.from(e.options).some(o=>o.value==='trigger')){const o=document.createElement('option');o.value='trigger';o.textContent='Immediate Gann trigger';e.insertBefore(o,e.firstChild)}}ensureTrigger();
function clearOld(){const res=$('res');if(res)res.classList.add('hide');['net','ntr','win','pf','dd','avg','kt','ksl','kl','ksh','best','worst'].forEach(id=>{const e=$(id);if(e)e.textContent='—'});const e=$('eq');if(e)e.innerHTML='';const m=$('months');if(m)m.innerHTML='';const t=$('trades');if(t)t.innerHTML='';}
function set(p,name){Object.entries(p).forEach(([k,v])=>{const e=$(k);if(e)e.value=v});$('dflt').classList.toggle('v',name==='Original Production 7750');cb.classList.toggle('v',name==='Later · 1-Min Close');rb.classList.toggle('v',name==='Re-entry Version');clearOld();
if(name==='Original Production 7750'){note.innerHTML='<b>Original Production 7750</b> · exact source screenshot: 05 Sep 2025 → 15 Sep 2026. First Support/Resistance touch becomes Square-of-9 input. After that touch, the first Gann Buy/Sell trigger creates the only trade of the day. Entry = exact Gann trigger. Stop = opposite Gann level. Target = exactly 100 points. Historical reference: 236 trades · 133 wins / 103 losses · 56.4% win · +7,750.3 points · 104 targets · 95 stop exits · losing streak 5.';chips.innerHTML='<span class=chip>05 Sep 2025 → 15 Sep 2026</span><span class=chip>WMA .382</span><span class=chip>5m first touch</span><span class=chip>Exact Gann trigger entry</span><span class=chip>100 pt target</span><span class=chip>Opposite Gann SL</span><span class=chip>ONE trade/day</span><span class=chip>No re-entry</span>'}
else if(name==='Later · 1-Min Close'){note.innerHTML='<b>Later · 1-Min Close</b> · later research variant: waits for a 1-minute candle close beyond Buy Above / Sell Below and enters at that close.';chips.innerHTML='<span class=chip>WMA .382</span><span class=chip>5m first touch</span><span class=chip>1m close</span><span class=chip>100 pt target</span><span class=chip>ONE trade/day</span>'}
else{note.innerHTML='<b>Re-entry Version</b> · immediate Gann trigger entry with multiple same-day re-entries after exits.';chips.innerHTML='<span class=chip>WMA .382</span><span class=chip>5m first touch</span><span class=chip>Exact Gann trigger</span><span class=chip>100 pt target</span><span class=chip>Unlimited re-entry</span>'}
const st=$('stat');if(st)st.textContent=name+' loaded. Old result cleared — click Run Backtest for a fresh result.';}
$('dflt').onclick=()=>set(PROD,'Original Production 7750');cb.onclick=()=>set(CLOSE,'Later · 1-Min Close');rb.onclick=()=>set(REENTRY,'Re-entry Version');set(PROD,'Original Production 7750');})();