(()=>{
  const gann=document.getElementById('gann');
  if(!gann||document.getElementById('realtime-alert-centre'))return;
  const style=document.createElement('style');
  style.textContent=`
  .ra-wrap{display:grid;gap:14px}.ra-top{display:flex;gap:12px;align-items:flex-start;justify-content:space-between;flex-wrap:wrap}.ra-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.ra-card{background:#fff;border:1px solid #e5ded9;border-radius:16px;padding:18px}.ra-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:12px}.ra-kpi{background:#f7f4f1;border-radius:10px;padding:10px}.ra-kpi span{display:block;color:#756d79;font-size:10px;text-transform:uppercase}.ra-kpi b{display:block;margin-top:4px;font-size:17px}.ra-state{font-size:25px;font-weight:900;margin:5px 0}.ra-alert{color:#11845f}.ra-wait{color:#a56a12}.ra-bad{color:#c43c4b}.ra-table{width:100%;border-collapse:collapse;font-size:12px;margin-top:12px}.ra-table th,.ra-table td{padding:9px;border-bottom:1px solid #eee;text-align:left}.ra-actions{display:flex;gap:8px;flex-wrap:wrap}.ra-btn{border:1px solid #e5ded9;background:#fff;border-radius:9px;padding:9px 12px;font-weight:750;cursor:pointer}.ra-btn.primary{background:#25142e;color:#fff;border-color:#25142e}.ra-rules{font-size:12px;line-height:1.6;color:#756d79}.ra-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#aaa;margin-right:6px}@media(max-width:850px){.ra-grid{grid-template-columns:1fr}.ra-kpis{grid-template-columns:repeat(2,1fr)}}`;
  document.head.appendChild(style);

  const pane=document.createElement('div');pane.id='realtime-alert-centre';pane.className='ra-wrap';
  pane.innerHTML=`<div class="ra-top"><div><h1 style="margin:0">Live Entry Alert Centre</h1><div class="sub">Zerodha-powered alerts only. Existing 7575 execution remains separate and unchanged.</div></div><div class="ra-actions"><label class="pill"><input id="raNotify" type="checkbox" checked> Sound + browser notification</label><button id="raStart" class="ra-btn primary">Start monitoring</button><button id="raStop" class="ra-btn">Stop</button></div></div>
  <div class="ra-grid"><section class="ra-card"><div class="ra-top"><div><b>NIFTY 39-trade engine</b><div class="muted">39 trades · 35 wins · 4 losses · retests allowed</div></div><span id="raNTime" class="pill">—</span></div><div id="raNState" class="ra-state ra-wait">WAITING</div><div id="raNMsg" class="muted">Start monitoring.</div><div class="ra-kpis"><div class="ra-kpi"><span>Side</span><b id="raNSide">—</b></div><div class="ra-kpi"><span>Entry</span><b id="raNEntry">—</b></div><div class="ra-kpi"><span>Stop</span><b id="raNStop">—</b></div><div class="ra-kpi"><span>Target</span><b id="raNTarget">—</b></div><div class="ra-kpi"><span>RSI 1m</span><b id="raNRsi">—</b></div><div class="ra-kpi"><span>WMA Ref.</span><b id="raNRef">—</b></div><div class="ra-kpi"><span>Gann</span><b id="raNGann">—</b></div><div class="ra-kpi"><span>Spot</span><b id="raNSpot">—</b></div></div></section>
  <section class="ra-card"><div class="ra-top"><div><b>NIFTY 100 Stock A+</b><div class="muted">Locked 11/11 rules · fresh cross only · no retest</div></div><button id="raRefreshStocks" class="ra-btn">Refresh NIFTY100</button></div><div id="raSState" class="ra-state ra-wait">IDLE</div><div id="raSMsg" class="muted">Press refresh or start monitoring.</div><div class="ra-kpis"><div class="ra-kpi"><span>Scanned</span><b id="raScanned">0/100</b></div><div class="ra-kpi"><span>Qualified</span><b id="raQualified">0</b></div><div class="ra-kpi"><span>Watching</span><b id="raWatching">0</b></div><div class="ra-kpi"><span>Updated</span><b id="raUpdated">—</b></div></div></section></div>
  <section class="ra-card"><b>Qualified alerts</b><div style="overflow:auto"><table class="ra-table"><thead><tr><th>Engine</th><th>Symbol</th><th>Side</th><th>Time</th><th>Entry</th><th>SL</th><th>Target</th><th>RSI</th></tr></thead><tbody id="raAlerts"><tr><td colspan="8">No live entry alert.</td></tr></tbody></table></div></section>
  <section class="ra-card"><b>Stock candidates and exact status</b><div style="overflow:auto"><table class="ra-table"><thead><tr><th>Symbol</th><th>Side</th><th>Gann</th><th>Body</th><th>RSI 1m</th><th>RSI 5m</th><th>Status / failed condition</th></tr></thead><tbody id="raCandidates"><tr><td colspan="7">No candidates loaded.</td></tr></tbody></table></div></section>
  <section class="ra-card"><details><summary><b>Frozen rule definitions</b></summary><div id="raRules" class="ra-rules" style="margin-top:10px">Loading…</div></details></section>`;
  gann.prepend(pane);
  const $=id=>document.getElementById(id),fmt=x=>Number.isFinite(Number(x))?Number(x).toFixed(2):'—';let timer=null,stockTimer=null,nifty=null,stocks={qualified:[],candidates:[]};
  async function api(url,opt){const r=await fetch(url,opt),j=await r.json();if(!r.ok)throw Error(j.detail||`HTTP ${r.status}`);return j}
  function notify(row,engine){if(!row?.signal_key||!$('raNotify').checked)return;const key='mio-alert-'+row.signal_key;if(localStorage.getItem(key))return;localStorage.setItem(key,new Date().toISOString());if(Notification.permission==='default')Notification.requestPermission();if(Notification.permission==='granted')new Notification(`${engine}: ENTER ${row.side}`,{body:`${row.symbol||'NIFTY'} at ${fmt(row.entry)} · SL ${fmt(row.stop)} · Target ${fmt(row.target)}`});try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=920;g.gain.value=.14;o.start();o.stop(a.currentTime+.45)}catch{}}
  function renderAlerts(){const rows=[];if(nifty?.state==='ALERT')rows.push({engine:'NIFTY 39',symbol:'NIFTY',...nifty});(stocks.qualified||[]).forEach(x=>rows.push({engine:'Stock A+',...x}));$('raAlerts').innerHTML=rows.length?rows.map(x=>`<tr><td>${x.engine}</td><td>${x.symbol||'NIFTY'}</td><td>${x.side||'—'}</td><td>${String(x.entry_time||'').slice(11,19)||'—'}</td><td>${fmt(x.entry)}</td><td>${fmt(x.stop)}</td><td>${fmt(x.target)}</td><td>${fmt(x.rsi1)}</td></tr>`).join(''):'<tr><td colspan="8">No live entry alert.</td></tr>';rows.forEach(x=>notify(x,x.engine))}
  async function scanNifty(){try{nifty=await api('/api/live/alerts/nifty39');$('raNState').textContent=nifty.state;$('raNState').className='ra-state '+(nifty.state==='ALERT'?'ra-alert':nifty.state.includes('REJECT')?'ra-bad':'ra-wait');$('raNMsg').textContent=nifty.message||'';$('raNTime').textContent=(nifty.latest_time||'').slice(11,19)||'—';$('raNSide').textContent=nifty.side||'—';$('raNEntry').textContent=fmt(nifty.entry);$('raNStop').textContent=fmt(nifty.stop);$('raNTarget').textContent=fmt(nifty.target);$('raNRsi').textContent=fmt(nifty.rsi1);$('raNRef').textContent=fmt(nifty.reference_price);$('raNGann').textContent=fmt(nifty.gann_trigger);$('raNSpot').textContent=fmt(nifty.latest_close);renderAlerts()}catch(e){$('raNState').textContent='ERROR';$('raNState').className='ra-state ra-bad';$('raNMsg').textContent=e.message}}
  function renderStocks(){const q=stocks.qualified||[],c=stocks.candidates||[];$('raSState').textContent=stocks.status||'IDLE';$('raSState').className='ra-state '+(q.length?'ra-alert':stocks.status==='ERROR'?'ra-bad':'ra-wait');$('raSMsg').textContent=stocks.error||`${q.length} qualified; ${c.length} passed opening filters.`;$('raScanned').textContent=`${stocks.scanned||0}/${stocks.total||100}`;$('raQualified').textContent=q.length;$('raWatching').textContent=c.length;$('raUpdated').textContent=(stocks.updated_at||'').slice(11,19)||'—';$('raCandidates').innerHTML=c.length?c.map(x=>`<tr><td>${x.symbol}</td><td>${x.side||'—'}</td><td>${fmt(x.gann_trigger)}</td><td>${fmt(x.body)}</td><td>${fmt(x.rsi1)}</td><td>${fmt(x.rsi5)}</td><td>${x.status}${x.failed?.length?' · '+x.failed.join(', '):''}</td></tr>`).join(''):'<tr><td colspan="7">No opening-qualified candidates.</td></tr>';renderAlerts()}
  async function pollStocks(){try{stocks=await api('/api/live/alerts/stocks');renderStocks()}catch(e){$('raSState').textContent='ERROR';$('raSMsg').textContent=e.message}}
  async function refreshStocks(){try{stocks=await api('/api/live/alerts/stocks/refresh',{method:'POST'});renderStocks();clearInterval(stockTimer);stockTimer=setInterval(pollStocks,5000)}catch(e){$('raSMsg').textContent=e.message}}
  async function rules(){try{const x=await api('/api/live/alerts/rules');$('raRules').innerHTML=`<b>NIFTY 39</b><br>${x.nifty39.entry}<br>${x.nifty39.windows}<br>${x.nifty39.gap_exception}<br>${x.nifty39.exit}<br><br><b>Stock A+</b><br>${x.stock_aplus.opening}<br>${x.stock_aplus.entry}<br>${x.stock_aplus.windows}<br>${x.stock_aplus.exit}`}catch(e){$('raRules').textContent=e.message}}
  $('raStart').onclick=()=>{scanNifty();refreshStocks();clearInterval(timer);timer=setInterval(scanNifty,15000)};$('raStop').onclick=()=>{clearInterval(timer);clearInterval(stockTimer);timer=stockTimer=null};$('raRefreshStocks').onclick=refreshStocks;rules();
})();
