from pathlib import Path
p=Path('/app/app/main.py')
s=p.read_text(encoding='utf-8')
if 'from .weekly_wma_gann import run_weekly' not in s:
    s=s.replace('from .strategy_lab import run_lab','from .strategy_lab import run_lab\nfrom .weekly_wma_gann import run_weekly')
block='''\n\nclass WeeklyWmaGannRequest(BaseModel):\n    symbol:str='NIFTY 50'\n    instrument_token:int|None=None\n    from_date:date\n    to_date:date\n    wma_factor:float=.382\n    gann_step:float=.125\n    target_points:float=100.0\n    gap_near_target_points:float=30.0\n    same_bar_policy:str='stop_first'\n\n@app.post('/api/weekly/backtest')\ndef weekly_wma_gann_backtest(req:WeeklyWmaGannRequest):\n    if req.from_date>=req.to_date:\n        raise HTTPException(400,'From date must be before To date')\n    try:\n        inst={'symbol':req.symbol,'instrument_token':req.instrument_token} if req.instrument_token else resolve_symbol(req.symbol)\n        df=fetch_minutes(int(inst['instrument_token']),req.from_date,req.to_date)\n        if df.empty:\n            raise RuntimeError('No 1-minute candles returned by Zerodha for this range')\n        summary,trades,attempts=run_weekly(df,req.wma_factor,req.gann_step,req.target_points,req.gap_near_target_points,req.same_bar_policy)\n        return {\n            'source':'Zerodha Kite 1-minute historical data',\n            'strategy':'Weekly WMA-Gann',\n            'symbol':inst.get('symbol',req.symbol),\n            'instrument_token':int(inst['instrument_token']),\n            'candles':len(df),\n            'summary':summary,\n            'trades':trades,\n            'attempts':attempts,\n            'config':req.model_dump(),\n            'rules':{\n                'anchor':'Tuesday expiry -> Wednesday first attempt',\n                'roll':'If no valid Wednesday trade, recalculate Wednesday H/L/C for Thursday; then Thursday H/L/C for Friday',\n                'entry':'First 5-minute candle CLOSE beyond Gann Buy/Sell trigger after first WMA Support/Resistance touch',\n                'target':'100 points from actual 5-minute close entry',\n                'stop':'Opposite Gann boundary',\n                'weekly_limit':'Maximum one trade per week',\n                'gap_filter':'Skip candidate day when opening price is already within the configured buffer of the theoretical 100-point target from the Gann trigger'\n            }\n        }\n    except Exception as e:\n        raise HTTPException(400,str(e))\n'''
if "@app.post('/api/weekly/backtest')" not in s:
    s += block
p.write_text(s,encoding='utf-8')
print('Weekly WMA-Gann API wired')
